.PHONY: clean All

All:
	@echo "----------Building project:[ AX3292-hello-atbm - Debug ]----------"
	@$(MAKE) -f  "AX3292-hello-atbm.mk" && $(MAKE) -f  "AX3292-hello-atbm.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ AX3292-hello-atbm - Debug ]----------"
	@$(MAKE) -f  "AX3292-hello-atbm.mk" clean
