#include"uiWin.h"

enum
{
	PHOTO_SCORE_MD_ID=0,
	PHOTO_SCORE_TIPS_ID,
	PHOTO_SCORE_STR1_ID,
	PHOTO_SCORE_STR2_ID,
	//PHOTO_SCORE_EXE_MAIN_ID,
	PHOTO_SCORE_MAX_ID
};
static widgetCreateInfor photoscoreWin[] =
{

	createFrameWin(Rx(0),Ry(0), Rw(320),Rh(240),R_COLOR_TRANSFER,WIN_ABS_POS),

	//createStringIcon(VIDEO_STR_ID,  Rx(0), Ry(215), Rw(320), Rh(25),R_ID_STR_VIDEO_STANDARD,ALIGNMENT_CENTER, R_COLOR_YELLOW,0),
	createImageIcon(PHOTO_SCORE_MD_ID,     Rx(90), Ry(30), Rw(140), Rh(110), /*R_ID_ICON_MTPHOTOFOCUSRED*/R_ID_ICON_MTBATTERY0,ALIGNMENT_CENTER),
	createImageIcon(PHOTO_SCORE_TIPS_ID,   Rx(7), Ry(190), Rw(304), Rh(48), R_ID_ICON_MTPHOTOSCORETIPS,ALIGNMENT_CENTER),
	createStringIcon(PHOTO_SCORE_STR1_ID,  Rx(60), Ry(200), Rw(80), Rh(25),R_ID_STR_PHOTO_DETECTION,ALIGNMENT_RIGHT, R_COLOR_YELLOW,0),
	createStringIcon(PHOTO_SCORE_STR2_ID,  Rx(145), Ry(203), Rw(80), Rh(25),"56",ALIGNMENT_LEFT, R_COLOR_RED,0),
#if TP_FUCTION
//	createImageIcon(PHOTO_SCORE_EXE_MAIN_ID,     Rx(270), Ry(200), Rw(48), Rh(48), R_ID_ICON_MENUBACK,ALIGNMENT_CENTER),
#endif
	widgetEnd(),
};




