#include"uiWin.h"

enum
{
	DATETIME_RECT_ID=0,
	DATETIME_YEAR,
	DATETIME_MON,
	DATETIME_DAY,
	DATETIME_HOUR,
	DATETIME_MIN,
	DATETIME_SEC,
	DATETIME_OK,
	//DATETIME_CANCEL,
	
	DATETIME_DATA1,
	DATETIME_DATA2,
	DATETIME_TIME1,
	DATETIME_TIME2,
	DATETIME_UP,
	DATETIME_DOWN,
	DATETIME_WIDGET_MANAGE
};
uint32 getDateTime1ResInfor(u16 id);

static widgetCreateInfor dateTime1Win[] =
{
	createFrameWin(Rx(58),Ry(50), Rw(250),Rh(160),R_COLOR_BLUE,WIN_ABS_POS),
	createRect(DATETIME_RECT_ID,    Rx(2),Ry(2), Rw(250-4),Rh(160-4),R_COLOR_GRAY2),
	createStringItem(DATETIME_YEAR, Rx(24), Ry(20), Rw(56), Rh(26),strToResId(" "),ALIGNMENT_CENTER, R_COLOR_WHITE,0,R_COLOR_GRAY2,ALIGNMENT_CENTER, R_COLOR_BLUE,0,R_COLOR_YELLOW),
	createStringIcon(DATETIME_DATA1,Rx(80),Ry(20), Rw(20),Rh(26),strToResId("/"),ALIGNMENT_CENTER, R_COLOR_WHITE,0),
	createStringItem(DATETIME_MON,  Rx(100),Ry(20), Rw(50), Rh(26),strToResId(" "),ALIGNMENT_CENTER, R_COLOR_WHITE,0,R_COLOR_GRAY2,ALIGNMENT_CENTER, R_COLOR_BLUE,0,R_COLOR_YELLOW),
	createStringIcon(DATETIME_DATA2,Rx(150),Ry(20), Rw(20),Rh(26),strToResId("/"),ALIGNMENT_CENTER, R_COLOR_WHITE,0),
	createStringItem(DATETIME_DAY,  Rx(170), Ry(20), Rw(50), Rh(26),strToResId(" "),ALIGNMENT_CENTER, R_COLOR_WHITE,0,R_COLOR_GRAY2,ALIGNMENT_CENTER, R_COLOR_BLUE,0,R_COLOR_YELLOW),
	createStringItem(DATETIME_HOUR,  Rx(60), Ry(66), Rw(30), Rh(26),strToResId(" "),ALIGNMENT_CENTER, R_COLOR_WHITE,0,R_COLOR_GRAY2,ALIGNMENT_CENTER, R_COLOR_BLUE,0,R_COLOR_YELLOW),
	createStringIcon(DATETIME_TIME1,Rx(90),Ry(66), Rw(20),Rh(26),strToResId(":"),ALIGNMENT_CENTER, R_COLOR_WHITE,0),
	createStringItem(DATETIME_MIN,   Rx(110), Ry(66), Rw(30), Rh(26),strToResId(" "),ALIGNMENT_CENTER, R_COLOR_WHITE,0,R_COLOR_GRAY2,ALIGNMENT_CENTER, R_COLOR_BLUE,0,R_COLOR_YELLOW),
	createStringIcon(DATETIME_TIME2,Rx(140),Ry(66), Rw(20),Rh(26),strToResId(":"),ALIGNMENT_CENTER, R_COLOR_WHITE,0),
	createStringItem(DATETIME_SEC,   Rx(160), Ry(66), Rw(30), Rh(26),strToResId(" "),ALIGNMENT_CENTER, R_COLOR_WHITE,0,R_COLOR_GRAY2,ALIGNMENT_CENTER, R_COLOR_BLUE,0,R_COLOR_YELLOW),
	createStringItem(DATETIME_OK,    Rx(25+35), Ry(112), Rw(60+70), Rh(26),strToResId(" "),ALIGNMENT_CENTER, R_COLOR_WHITE,0,R_COLOR_GRAY2,ALIGNMENT_CENTER, R_COLOR_BLUE,0,R_COLOR_YELLOW),
	//createStringItem(DATETIME_CANCEL,Rx(95+35), Ry(112), Rw(60), Rh(26),strToResId(" "),ALIGNMENT_CENTER, R_COLOR_WHITE,0,R_COLOR_GRAY3,ALIGNMENT_CENTER, R_COLOR_RED,0,R_COLOR_BLUE),

	//createImageIcon(DATETIME_UP,  Rx(30+15), Ry(0), Rw(20), Rh(20), R_ID_ICON_MTUP,ALIGNMENT_CENTER),
	//createImageIcon(DATETIME_DOWN,  Rx(30+15), Ry(46), Rw(20), Rh(20), R_ID_ICON_MTDOWN,ALIGNMENT_CENTER),
	createWidgetManage(DATETIME_WIDGET_MANAGE,DATETIME_YEAR,DATETIME_OK,getDateTime1ResInfor),
	widgetEnd(),
};



