#include"uiWin.h"

typedef enum
{
	THUMBNALL1_RECT_COLOR=0,
	THUMBNALL1_RECT_NO_COLOR,
	THUMBNALL1_STRING,
	THUMBNALL2_RECT_COLOR,
	THUMBNALL2_RECT_NO_COLOR,
	THUMBNALL2_STRING,
	THUMBNALL3_RECT_COLOR,
	THUMBNALL3_RECT_NO_COLOR,
	THUMBNALL3_STRING,
	THUMBNALL4_RECT_COLOR,
	THUMBNALL4_RECT_NO_COLOR,
	THUMBNALL4_STRING,
	THUMBNALL5_RECT_COLOR,
	THUMBNALL5_RECT_NO_COLOR,
	THUMBNALL5_STRING,
	THUMBNALL6_RECT_COLOR,
	THUMBNALL6_RECT_NO_COLOR,
	THUMBNALL6_STRING,
	
	/*THUMBNALL7_RECT_COLOR,
	THUMBNALL7_RECT_NO_COLOR,
	THUMBNALL7_STRING,
	THUMBNALL8_RECT_COLOR,
	THUMBNALL8_RECT_NO_COLOR,
	THUMBNALL8_STRING,
	THUMBNALL9_RECT_COLOR,
	THUMBNALL9_RECT_NO_COLOR,
	THUMBNALL9_STRING,*/
	THUMBNALL_PAGE,
}thumbnallID;
static thumbnallID thumbnallIDnum[]=
{
	THUMBNALL1_RECT_COLOR,
	THUMBNALL2_RECT_COLOR,
	THUMBNALL3_RECT_COLOR,
	THUMBNALL4_RECT_COLOR,
	THUMBNALL5_RECT_COLOR,
	THUMBNALL6_RECT_COLOR/*,
	THUMBNALL7_RECT_COLOR,
	THUMBNALL8_RECT_COLOR,
	THUMBNALL9_RECT_COLOR*/
};

#define	ROW		2
#define	COLUMN		3

#define T_INTERV	20
#define	B_INTERV	0
#define L_INTERV	4
#define R_INTERV	4

#define H_INTERV	4
#define V_INTERV	4
#define UNIT_W		((320-L_INTERV-R_INTERV-(COLUMN-1)*V_INTERV)/COLUMN)
#define	UNIT_H		((240-T_INTERV-B_INTERV-(ROW-1)*H_INTERV)/ROW)

#define THUMBNALL_NUM      (sizeof(thumbnallIDnum)/sizeof(thumbnallIDnum[0]))
#define SELECT_COLOR       R_COLOR_YELLOW
static widgetCreateInfor thumbnallWin[] =
{
	createFrameWin(Rx(0),Ry(0), Rw(320),Rh(240),R_COLOR_BLACK,WIN_ABS_POS),
	createRect(THUMBNALL1_RECT_COLOR,     Rx(L_INTERV),  Ry(T_INTERV), Rw(UNIT_W),Rh(UNIT_H),R_COLOR_TRANSFER),
	createRect(THUMBNALL1_RECT_NO_COLOR,  Rx(L_INTERV+1),   Ry(T_INTERV+1), Rw(UNIT_W-2),Rh(UNIT_H-2),R_COLOR_TRANSFER),
	createStringIcon(THUMBNALL1_STRING,   Rx(L_INTERV+50),  Ry(T_INTERV), Rw(50),Rh(20)," ",ALIGNMENT_RIGHT, R_COLOR_WHITE,0),

	createRect(THUMBNALL2_RECT_COLOR,     Rx(L_INTERV+(UNIT_W+V_INTERV)*1), Ry(T_INTERV), Rw(UNIT_W),Rh(UNIT_H),R_COLOR_TRANSFER),
	createRect(THUMBNALL2_RECT_NO_COLOR,  Rx((L_INTERV+(UNIT_W+V_INTERV)*1)+1), Ry(T_INTERV+1), Rw(UNIT_W-2),Rh(UNIT_H-2),R_COLOR_TRANSFER),
	createStringIcon(THUMBNALL2_STRING,   Rx((L_INTERV+(UNIT_W+V_INTERV)*1)+50), Ry(T_INTERV), Rw(50),Rh(20)," ",ALIGNMENT_RIGHT, R_COLOR_WHITE,0),

	createRect(THUMBNALL3_RECT_COLOR,     Rx(L_INTERV+(UNIT_W+V_INTERV)*2), Ry(T_INTERV), Rw(UNIT_W),Rh(UNIT_H),R_COLOR_TRANSFER),
	createRect(THUMBNALL3_RECT_NO_COLOR,  Rx((L_INTERV+(UNIT_W+V_INTERV)*2)+1), Ry(T_INTERV+1), Rw(UNIT_W-2),Rh(UNIT_H-2),R_COLOR_TRANSFER),
	createStringIcon(THUMBNALL3_STRING,   Rx((L_INTERV+(UNIT_W+V_INTERV)*2)+50), Ry(T_INTERV), Rw(50),Rh(20)," ",ALIGNMENT_RIGHT, R_COLOR_WHITE,0),


	
	createRect(THUMBNALL4_RECT_COLOR,     Rx(L_INTERV),  Ry(T_INTERV+UNIT_H+H_INTERV), Rw(UNIT_W),Rh(UNIT_H),R_COLOR_TRANSFER),
	createRect(THUMBNALL4_RECT_NO_COLOR,  Rx(L_INTERV+1),   Ry((T_INTERV+UNIT_H+H_INTERV)+1), Rw(UNIT_W-2),Rh(UNIT_H-2),R_COLOR_TRANSFER),
	createStringIcon(THUMBNALL4_STRING,   Rx(L_INTERV+50),  Ry(T_INTERV+UNIT_H+H_INTERV), Rw(50),Rh(20)," ",ALIGNMENT_RIGHT, R_COLOR_WHITE,0),

	createRect(THUMBNALL5_RECT_COLOR,     Rx(L_INTERV+(UNIT_W+V_INTERV)*1), Ry(T_INTERV+UNIT_H+H_INTERV), Rw(UNIT_W),Rh(UNIT_H),R_COLOR_TRANSFER),
	createRect(THUMBNALL5_RECT_NO_COLOR,  Rx((L_INTERV+(UNIT_W+V_INTERV)*1)+1), Ry((T_INTERV+UNIT_H+H_INTERV)+1), Rw(UNIT_W-2),Rh(UNIT_H-2),R_COLOR_TRANSFER),
	createStringIcon(THUMBNALL5_STRING,   Rx((L_INTERV+(UNIT_W+V_INTERV)*1)+50), Ry(T_INTERV+UNIT_H+H_INTERV), Rw(50),Rh(20)," ",ALIGNMENT_RIGHT, R_COLOR_WHITE,0),

	createRect(THUMBNALL6_RECT_COLOR,     Rx(L_INTERV+(UNIT_W+V_INTERV)*2), Ry(T_INTERV+UNIT_H+H_INTERV), Rw(UNIT_W),Rh(UNIT_H),R_COLOR_TRANSFER),
	createRect(THUMBNALL6_RECT_NO_COLOR,  Rx((L_INTERV+(UNIT_W+V_INTERV)*2)+1), Ry((T_INTERV+UNIT_H+H_INTERV)+1), Rw(UNIT_W-2),Rh(UNIT_H-2),R_COLOR_TRANSFER),
	createStringIcon(THUMBNALL6_STRING,   Rx((L_INTERV+(UNIT_W+V_INTERV)*2)+50), Ry(T_INTERV+UNIT_H+H_INTERV), Rw(50),Rh(20)," ",ALIGNMENT_RIGHT, R_COLOR_WHITE,0),
/*
	createRect(THUMBNALL7_RECT_COLOR,     Rx(5 ),  Ry(168), Rw(100),Rh(70),R_COLOR_TRANSFER),
	createRect(THUMBNALL7_RECT_NO_COLOR,  Rx(6),   Ry(169), Rw(98),Rh(68),R_COLOR_TRANSFER),
	createStringIcon(THUMBNALL7_STRING,   Rx(55),  Ry(168), Rw(50),Rh(20)," ",ALIGNMENT_RIGHT, R_COLOR_WHITE,0),
	createRect(THUMBNALL8_RECT_COLOR,     Rx(110), Ry(168), Rw(100),Rh(70),R_COLOR_TRANSFER),
	createRect(THUMBNALL8_RECT_NO_COLOR,  Rx(111), Ry(169), Rw(98),Rh(68),R_COLOR_TRANSFER),
	createStringIcon(THUMBNALL8_STRING,   Rx(160), Ry(168), Rw(50),Rh(20)," ",ALIGNMENT_RIGHT, R_COLOR_WHITE,0),
	createRect(THUMBNALL9_RECT_COLOR,     Rx(215), Ry(168), Rw(100),Rh(70),R_COLOR_TRANSFER),
	createRect(THUMBNALL9_RECT_NO_COLOR,  Rx(216), Ry(169), Rw(98),Rh(68),R_COLOR_TRANSFER),
	createStringIcon(THUMBNALL9_STRING,   Rx(265), Ry(168), Rw(50),Rh(20)," ",ALIGNMENT_RIGHT, R_COLOR_WHITE,0),
*/
	createStringIcon(THUMBNALL_PAGE,      Rx(130), Ry(0), Rw(60),Rh(20)," ",ALIGNMENT_CENTER, R_COLOR_WHITE,0),
	widgetEnd(),
};

static void thumbnallSelect(winHandle handle,u32 num,bool select)
{
	if(select)
	{
		winSetfgColor(winItem(handle,thumbnallIDnum[num]),SELECT_COLOR);
	}
	else
	{
		winSetfgColor(winItem(handle,thumbnallIDnum[num]),R_COLOR_TRANSFER);
	}
}

static void thumbnallShowPage(winHandle handle,u32 curpage,u32 totalPage)
{
	static char str[30];
	int n;
	
	curpage+= 1;
	
	n=uintToString(&str,30,curpage);
	str[n]='/';
	uintToString(&str[n+1],30-n-1,totalPage);
	winSetResid(winItem(handle,THUMBNALL_PAGE),strToResId(str));
}

