#ifndef __SYSCOMMON_H
#define __SYSCOMMON_H

// 定义屏幕尺寸,在ctrldef.c中会调用
// 其他地方也会调用,例如在sd卡升级时,生成的进度条使用到这个参数

// 主要区分当屏尺寸一样时,属于哪种模式
#define CHILDREN_320x240 0	// 儿童相机--320x240
#define DVRUNNING_220x176 1 // 运动dv--220x176
#define DVRUNNING_320x240 2 // 运动dv--320x240
#define CHILDREN_480x320 4	// 儿童相机--320x240

// 定义尺寸需要和SCREEN_W、SCREEN_H一致
#define APPLY_MODE CHILDREN_320x240

#if APPLY_MODE == DVRUNNING_320x240 || APPLY_MODE == CHILDREN_320x240
#define SCREEN_W 320 // 220  320
#define SCREEN_H 240 // 176	 240

#elif APPLY_MODE == DVRUNNING_220x176
#define SCREEN_W 220 // 220  320
#define SCREEN_H 176 // 176	 240

#elif APPLY_MODE == CHILDREN_480x320
#define SCREEN_W 480 // 220  320
#define SCREEN_H 320 // 176	 240

#endif

#define UPDATE_BIN "1:ramdisk.bin" // 需要升级的bin文件名

#define SETTINGNUM 25
#define APPSETTINGNUM 15

// 图片质量
#define QUALITYMAX 3
#define QUALITYMIN 0
#define QUALITYNAME "quality"

// 语言选择
#define LANGUAGEMAX 4
#define LANGUAGEMIN 0
#define LANGUAGENAME "language"

// 循环录影
#define LOOPMAX 6
#define LOOPMIN 0
#define LOOPNAME "LOOP"

// 分辨率选择
#define DPIMAX 4
#define DPIMIN 0
#define DPINAME "DPI"

// 分辨率选择
#define WIFIDPIMAX 3
#define WIFIDPIMIN 0
#define WIFIDPINAME "WIFIDPI"

// 录像声音
#define RECSOUNDMAX 2
#define RECSOUNDMIN 0
#define RECSOUNDNAME "recsound"

// 白平衡
#define AWBMAX 6
#define AWBMIN 0
#define AWBNAME "awb"

// 曝光
#define EVMAX 5
#define EVMIN 0
#define EVNAME "EV"

// 按键声音
#define KEYSOUNDMAX 2
#define KEYSOUNDMIN 0
#define KEYSOUNDNAME "keysound"

// 按键声音
#define SAVEMAX 2
#define SAVEMIN 0
#define SAVENAME "save"

// 拍照
#define TAKEPHOTOMAX 2
#define TAKEPHOTOMIN 0
#define TAKEPHOTONAME "takephoto"

// 录像
#define RECORDMAX 3
#define RECORDMIN 0
#define RECORDNAME "record"

// wifi  预览质量
#define WIFIQUALITYMAX 3
#define WIFIQUALITYMIN 0
#define WIFIQUALITYNAME "WIFIpreview"

// 移动侦测
#define MDTMAX 2
#define MDTMIN 0
#define MDTNAME "MDT"

// 格式化
#define FORMATMAX 2
#define FORMATMIN 0
#define FORMATNAME "FORMAT"

// 连拍
#define PHOTOBURSTMAX 5
#define PHOTOBURSTMIN 0
#define PHOTOBURSTNAME "photoBurst"

// 定时
#define PHOTOTIMELAPSEMAX 5
#define PHOTOTIMELAPSEMIN 0
#define PHOTOTIMELAPSENAME "photoTimeLapse"

// wifiSSID  WIFIPW
// 默认wifi名字
#define DEFAULT_SSID "ActionCam"
#define DEFAULT_PW "123456789"

#define WIFISSID "WIFISSID"
#define WIFIPW "WIFIPW"

// MAC
#define DEFAULT_MAC ""
#define WIFIMAC "WIFIMAC"

// 循环录影
#define SETDATEMAX 1
#define SETDATEMIN 0
#define SETDATENAME "DATE"

// 恢复出厂设置
#define RESTOREMAX 2
#define RESTOREMIN 0
#define RESTORENAME "RESTORE"

// 日期标签
#define WATERMARKMAX 2
#define WATERMARKMIN 0
#define WATERMARKNAME "WATERMARK"

// 自动关屏幕
#define SCREENSAVEMAX 4
#define SCREENSAVEMIN 0
#define SCREENSAVENAME "SCREENSAVE"

// 自动关机
#define AUTOPOWEROFFMAX 5
#define AUTOPOWEROFFMIN 0
#define AUTOPOWEROFFNAME "AUTOPOWEROFF"

// 删除文件
#define DELFILEMAX 2
#define DELFILEMIN 0
#define DELFILENAME "DELFILE"

// 文件锁
#define FILELOCKMAX 4
#define FILELOCKMIN 0
#define FILELOCKNAME "FILELOCK"

// 软件版本
#define SOFTWAREVERSIONNAME "VERSION"

// 锐度
#define ACUTANCEMAX 3
#define ACUTANCEMIN 0
#define ACUTANCENAME "ACUTANCE"

// 图片分辨率选择
#define PDPIMAX 8
#define PDPIMIN 0
#define PDPINAME "PDPI"

// 儿童相机分辨率选择
#define CHILDRENDPIMAX 2
#define CHILDRENDPIMIN 0
#define CHILDRENDPINAME "CHILDRENDPI"

/*****************自定义控件的ID********************/
// 如果客户需要添加,则可能需要添加到列表最后,如果在中间插入会导致库变动
enum USER_CTRL_ID
{
	// 主菜单
	MENU_TOP = 3,

	// 儿童相机主界面
	MAIN_UI,
	MAIN_UI_SELECT,
	MAIN_UI_BATTERY,

	// 录像界面
	REC_RECORD,	  // 录像提示红点图标
	REC_LOOPREC,  // 循环录像图标
	REC_SOUND,	  // 录像声音图标
	REC_QUALITY,  // 录像质量字符串
	REC_SDCARD,	  // sd卡图标
	REC_BATTERY,  // 录像界面的电池图标
	REC_RTC,	  // 录像界面的时钟图标
	REC_TIMER,	  // 录像界面的录像时间
	REC_NOTICE,	  // 弹窗通知用的标志
	REC_FILEFULL, // SD卡满
	REC_WIFISSID, // WiFi名称字符串
	REC_WIFIPW,	  // wifi密码字符串
	REC_WIFI_NOTICE,
	REC_MDT_ICON,
	REC_FRAME,
	REC_TOP1,
	REC_TOP2,
	/**/
	REC_NP0,
	REC_NP1,
	REC_NP2,
	REC_NP3,
	REC_NP4,
	REC_NP5,
	REC_NP6,
	REC_NP7,
	REC_NP8,
	REC_NP9,
	REC_NP10,
	REC_NP11,
	REC_NP12,

	// 拍照界面
	PHO_PHOTO,	 // 显示拍照图标
	PHO_QUALITY, // 拍照质量字符串
	PHO_SDCARD,	 // sd卡图标
	PHO_FILEFULL,
	PHO_BATTERY, // 拍照界面的电池图标
	PHO_RTC,	 // 拍照界面的时钟图标
	PHO_TIMING,	 // 延时拍照图标(倒计时图标)
	PHO_MODE,
	PHO_TIMING2, // 延时拍照图标(显示是否有定时拍照)
	PHO_CONTINU, // 连拍的图标
	PHO_TAKING,	 // 拍照瞬间显示的图标
	PHO_NOTICE,	 // 弹窗通知用的标志
	PHO_REMAIN,	 // 剩余的张数
	PHO_FRAME,
	PHO_TOP1,
	PHO_TOP2,

	// 浏览图片界面
	BRO_BROWSE,	  // 浏览图标
	BRO_LOCK,	  // 浏览图标
	BRO_FILENAME, // 文件名
	BRO_NOTICE,	  // 弹窗通知用的标志
	BRO_NOSDCARD,
	BRO_BATTERY,
	BRO_NOFILE,

	// 回放界面
	PLA_PLAYBACK, // 浏览图标
	PLA_FILENAME, // 文件名
	PLA_NOTICE,	  // 弹窗通知用的标志
	PLA_TIMER,
	PLA_VOLUME,

	// 设置菜单界面
	RECORD_PREVIEW_MENU,
	RECORD_MENU,
	WIIF_MENU,
	WIFI_MODE1_MENU,
	WIFI_MENUBAR,
	SETTING_MENUBAR,
	PLAYBACK_MENUBAR,
	TAKEPHOTO_PREVIEW_MENU,
	TAKEPHOTO_MENU,
	BROWSE_PHOTO_MENU,
	PLAYBACK_MENU,
	ENTER_PLAYBACK_MENU,
	SET_MENU,

	// 手动设置时间

	SET_HOUR, // 时
	SET_MIN,
	SET_YEAR,
	SET_MONTH,
	SET_DAY,
	SET_MODE,

	// 手动设置时间

	SET_QUALITY,		 // 图片质量
	SET_LANGUAGE,		 // 语言设置
	SET_LOOP_REC,		 // 循环录像
	SET_KEYSOUND,		 // 按键声音
	SET_REC_DPI,		 // 分辨率设置
	SET_RECSOUND,		 // 录像声音
	SET_AWB,			 // 白平衡设置
	SET_EV,				 // 曝光设置
	SET_MDT,			 // 移动侦测
	SET_SHOOTING_COUNT,	 // 设置连拍数量
	SET_TAKEPHOTO_TIMER, // 设置定时
	SET_FORMAT,			 // 格式化
	SET_TIMEMUNE,		 // 日期设置
	SET_RESTORE_FACTORY, // 恢复出厂设置
	SET_TIMESTAMP,		 // 日期标签
	SET_SSID,
	SET_PASSWORD,
	SET_LOCK,
	SET_DEL,
	SET_SCREEN_OFF,
	SET_POWER_OFF,
	SET_VER,
	SET_ACUITY,
	SET_LOCAL_DPI, // 本地图片分辨率设置

	SD_UPDATE_UI, // sd卡升级的ui
	USB_UI,		  // USB大容量储存
	CHARGE_UI,	  // 充电
	WIFI_CONN,	  // wifi连接数量
	WIFI_FLAG,	  // wifi指示,主要判断是否还在工作
	NES_WIFI_MODE,
	NES_SOUND,
	NES_NAME1,
	NES_NAME2,
	NES_NAME3,
	NES_NAME4,

	MP3_NAME,

	FORMAT_WINDOW,

	SETTING_PAGE, // 设置页面的页数

	OTHER_MODE_SELECT,
	NES_SELECT,	  // NES选中条
	NES_SINGLE,	  // NES单人模式
	NES_DOUBLE1P, // NES双人模式1P
	NES_DOUBLE2P, // NES双人模式2P

	// 测试用的
	REC_RECORDING, // 录像提示红点图标
	TEST_STRID1,
	TEST_STRID2,
	TEST_STRID3,
	TEST_STRID4,

	// 游戏
	BROWSE_BOX_MENU,

	BOXID_0,
	BOXID_1,
	BOXID_2,
	BOXID_3,
	BOXID_4,
	BOXID_5,
	BOXID_6,
	BOXID_7,
	BOXID_8,
	BOXID_9,
	BOXID_10,
	BOXID_11,
	BOXID_12,
	BOXID_13,
	BOXID_14,
	BOXID_15,
	BOXID_16,
	BOXID_17,
	BOXID_18,
	BOXID_19,
	BOXID_20,
	BOXID_21,
	BOXID_22,
	BOXID_23,
	BOXID_24,
	BOXID_25,
	BOXID_26,
	BOXID_27,
	BOXID_28,
	BOXID_29,
	BOXID_30,
	BOXID_31,
	BOXID_32,
	BOXID_33,
	BOXID_34,
	BOXID_35,
	BOXID_36,
	BOXID_37,
	BOXID_38,
	BOXID_39,
	BOXID_40,
	BOXID_41,
	BOXID_42,
	BOXID_43,
	BOXID_44,
	BOXID_45,
	BOXID_46,
	BOXID_47,
	BOXID_48,
	BOXID_49,
	BOXID_50,
	BOXID_51,
	BOXID_52,
	BOXID_53,
	BOXID_54,
	BOXID_55,
	BOXID_56,
	BOXID_57,
	BOXID_58,
	BOXID_59,
	BOXID_60,
	BOXID_61,
	BOXID_62,
	BOXID_63,
	BOXID_64,
	BOXID_65,
	BOXID_66,
	BOXID_67,
	BOXID_68,
	BOXID_69,
	BOXID_70,
	BOXID_71,
	BOXID_72,
	BOXID_73,
	BOXID_74,
	BOXID_75,
	BOXID_76,
	BOXID_77,
	BOXID_78,
	BOXID_79,

	THIRD_ID,
	OTHER_ID, // 其他模式,除了主界面模式就是其他模式(暂定有USB、升级两种)
	USB_MODE,
	MY_TEST_ID = 0xff00,
	// 空ID
	NULL_ID = 0xffff // 不设置id时填这个
};

// 跟excel里的id序号一致，复制过来
enum font_langid
{
	english = 1,
	schinese,
	tchinese,
	japanese,
	koera,
	russian,
	turkey,
	tai,
	czech,
	spanish,
	ukrainian,
	german,
	french,
	italian,
	portuguese,
	dutch,
	hebrew,
	polish
};

// 字符串的ID,与xls表格的一样

enum locale

{
	STR_LAN_ENGLISH = 1,
	STR_LAN_SCHINESE,
	STR_LAN_TCHINESE,
	STR_LAN_JAPANESE,
	STR_LAN_GERMAN,
	STR_LAN_FRECH,
	STR_LAN_RUSSIAN,
	STR_LAN_ITALIAN,
	STR_LAN_KOERA,
	STR_LAN_TAI,
	STR_LAN_HEBREW,
	STR_LAN_DUTCH,
	STR_LAN_UKRAINIAN,
	STR_LAN_SPANISH,
	STR_LAN_PORTUGUESE,
	STR_LAN_POLISH,
	STR_LAN_CZECH,
	STR_LAN_TURKEY,
	STR_UPDATE_START,
	STR_UPDATE_END,
	STR_COM_OFF,
	STR_COM_ON,
	STR_COM_OK,
	STR_COM_CANCEL,
	STR_COM_YES,
	STR_COM_NO,
	STR_COM_LOW,
	STR_COM_MIDDLE,
	STR_COM_HIGH,
	STR_COM_WAITING,
	STR_COM_50HZ,
	STR_COM_60HZ,
	STR_COM_P2_0,
	STR_COM_P1_0,
	STR_COM_P0_0,
	STR_COM_N1_0,
	STR_COM_N2_0,
	STR_COM_ALWAYSON,
	STR_COM_ECONOMIC,
	STR_COM_NORMAL,
	STR_COM_FINE,
	STR_TIM_1MIN,
	STR_TIM_2MIN,
	STR_TIM_3MIN,
	STR_TIM_5MIN,
	STR_TIM_10MIN,
	STR_TIM_2SEC,
	STR_TIM_5SEC,
	STR_SET_DATETIME,
	STR_SET_AUTOOFF,
	STR_SET_LANGUAGE,
	STR_SET_SCREENOFF,
	STR_SET_VIDEOROTATE,
	STR_SET_RESET,
	STR_SET_FORMAT,
	STR_SET_VERSION,
	STR_SET_RESOLUTION,
	STR_SET_LOOPRECORD,
	STR_SET_MOTIONDET,
	STR_SET_AUDIOREC,
	STR_SET_TIMESTRAMP,
	STR_SET_FILLIGHT,
	STR_SET_GSENSOR,
	STR_SET_PARKMODE,
	STR_SET_FASTVIEW,
	STR_SET_DELETECUR,
	STR_SET_DELETEALL,
	STR_SET_LOCKCUR,
	STR_SET_LOCKALL,
	STR_SET_UNLOCKCUR,
	STR_SET_UNLOCKALL,
	STR_SET_LOCK,
	STR_SET_DELETE,
	STR_SET_PLAYMODE,
	STR_SET_REPEATALL,
	STR_SET_REPEATRAD,
	STR_SET_REPEATSIG,
	STR_SET_AUDIOPLAY,
	STR_SET_VOLUME,
	STR_SET_THUMBNAIL,
	STR_SET_SETTING,
	STR_SET_VIDEO,
	STR_SET_PHOTO,
	STR_SET_PLAY,
	STR_SET_MUSIC,
	STR_SET_AUDIOMODE,
	STR_SET_USBMASS,
	STR_SET_USBCAM,
	STR_SET_BEEPSOUND,
	STR_SET_FREQUENCY,
	STR_SET_QUALITY,
	STR_SET_PROMT,
	STR_RES_240P,
	STR_RES_480P,
	STR_RES_480FHD,
	STR_RES_720P,
	STR_RES_1024P,
	STR_RES_1080P,
	STR_RES_1080FHD,
	STR_RES_1440P,
	STR_RES_3024P,
	STR_RES_QVGA,
	STR_RES_VGA,
	STR_RES_HD,
	STR_RES_FHD,
	STR_RES_12M,
	STR_RES_10M,
	STR_RES_8M,
	STR_RES_5M,
	STR_RES_3M,
	STR_RES_2M,
	STR_RES_1M,
	STR_SDC_NULL,
	STR_SDC_FULL,
	STR_SDC_ERROR,
	STR_FIL_NULL,
	STR_FIL_LOCKED,
	STR_FMT_ING,
	STR_FMT_SUCCESS,
	STR_FMT_FAIL,
	STR_PWR_LOW,
	STR_ISP_WHITEBL,
	STR_ISP_ISO,
	STR_ISP_ANTISHANK,
	STR_ISP_AUTO,
	STR_ISP_SOFT,
	STR_ISP_STRONG,
	STR_ISP_SUNLIGHT,
	STR_ISP_CLOUDY,
	STR_ISP_TUNGSTEN,
	STR_ISP_FLUORESCENT,
	STR_ISP_BLACKWHITE,
	STR_ISP_SEPIA,
	STR_ISP_ISO100,
	STR_ISP_ISO200,
	STR_ISP_ISO400,
	STR_ISP_WDR,
	STR_ISP_EXPOSURE,
	STR_PHOTO_TIME_SHOOT,
	STR_PHOTO_CONTINUE_SHOOT,
	STR_PHOTO_TIME_SHOOT0,
	STR_PHOTO_TIME_SHOOT3,
	STR_PHOTO_TIME_SHOOT5,
	STR_PHOTO_TIME_SHOOT10,
	STR_PHOTO_TIME_SHOOT20,
	STR_PHOTO_CONTINUE_SHOOT3,
	STR_PHOTO_CONTINUE_SHOOT5,
	STR_PHOTO_CONTINUE_SHOOT10,
	STR_TIM_3SEC,
	STR_TIM_10SEC,
	STR_TIM_15SEC,
	STR_TIM_30SEC,
	STR_DELETE_LOCK_FILE_TIP,
	STR_OPERATION_SUCCESSFUL,
	STR_OPERATION_FAILED,
	STR_DATA_SETTING,
	STR_RECOED_AUDIO,
	STR_LAN_ENGLISH2,
	STR_PHOTO_SET_TIME,
	STR_DATA_MODE1,
	STR_DATA_MODE2,
	STR_DATA_MODE3,
	STR_RESTORE_FACTORY,
	STR_DATE_LABEL,
	STR_SSID,
	STR_PW,
	STR_VER,
	STR_ACUITY,
	STR_RES_1_3M,
	STR_SET_PRESOLUTION,
	STR_USB_STORAGE,
	STR_USB_CAMERA,
	STR_SD_NO_FILE,

};

// 图片的ID,与xls表格的一样
enum icon
{
	ICONID_OPEN = 0,
	ICONID_BACK0,
	ICONID_BACK1,
	ICONID_BACKTOP,
	ICONID_BAT0,
	ICONID_BAT1,
	ICONID_BAT2,
	ICONID_BAT3,
	ICONID_BAT4,
	ICONID_CYC1MIN,
	ICONID_CYC2MIN,
	ICONID_CYC3MIN,
	ICONID_CYC5MIN,
	ICONID_CYC10MIN,
	ICONID_CYC10SEC,
	ICONID_CYCOFF,
	ICONID_DV_R,
	ICONID_DV_Y,
	ICONID_MENU1_1,
	ICONID_MENU1_2,
	ICONID_MENU1_3,
	ICONID_MENU1_4,
	ICONID_MENU1_5,
	ICONID_MENU1_6,
	ICONID_PHOTO,
	ICONID_SOUNDON,
	ICONID_SOUNDOFF,
	ICONID_WIFI,
	ICONID_SDOFF,
	ICONID_SDON,
	ICONID_Z1,
	ICONID_Z2,
	ICONID_Z3,
	ICONID_NULL,
	ICONID_SETTING,
	ICONID_PLAY,
	ICONID_Z4,
	ICONID_BAT5,
	ICONID_NOFILE,

	ICONID_PERSON,
	ICONID_ALLOW,
	ICONID_TREE,
	ICONID_BOX,
	ICONID_TARGET,
	ICONID_WALL,
	ICONID_BLKUIT,
	ICONID_BMENU2,

	ICONID_RECORD,
	ICONID_NP0,
	ICONID_NP1,
	ICONID_NP2,
	ICONID_NP3,
	ICONID_NP4,
	ICONID_NP5,
	ICONID_NP6,
	ICONID_NP7,
	ICONID_NP8,
	ICONID_NP9,
	ICONID_NP10,
	ICONID_NP11,
	ICONID_NP12,
	ICONID_PM,
	ICONID_LG,
	ICONID_VL,
	ICONID_AK,
	ICONID_MP,
	ICONID_MV,
	ICONID_EV,
	ICONID_MD,
	ICONID_FV,
	ICONID_CG,
	ICONID_FM,
	ICONID_DAT,
	ICONID_TIM,
	ICONID_DEF,
	ICONID_SSID,
	ICONID_PW,
	ICONID_PT,
	ICONID_DEL,
	ICONID_SSV,
	ICONID_APO,
	ICONID_VER,
	ICONID_ACUITY,
	ICONID_LOCK,
	ICONID_MOTION_DECTION_START,
	ICONID_BROWSE_MENU_PLAYBACK,
	ICONID_PAUSE,
	ICONID_BD1,
	ICONID_SD_UPDATE,
	ICONID_MAINMENU,
	ICONID_Z5,
	ICONID_CLOSE,
	ICONID_USB_MODE,
	ICONID_CYC20MIN,
	ICONID_AWB,
	ICONID_FILEFULL,
	ICONID_BURST,
	ICONID_TIMELAPSE,
	ICONID_SELECTL,
	ICONID_SELECTR,
	ICONID_SINGLE,
	ICONID_DOUBLE1P,
	ICONID_DOUBLE2P,
	ICONID_GAME_BG,
	ICONID_PRINTER,
	ICONID_FORMAT_S,

	ICONID_END, // excel的所有ID都在上面,下面是属于其他部分
	ICONID_BAT_SELF,

};

#endif
