/**@file sysid.h
 * @brief System pre-defined ID
 * @note
 * System-Engineers        can not #include sysid.h directly, uses sys-id.h instead.
 * Application-Engineers   can not #include sysid.h directly, uses sys-id.h instead.
 * Application-Engineers                                 can not modify sysid.h!
 * Configuration-Engineers can     #include sysid.h, but can not modify sysid.h!
 */

#ifndef __RESFS_SYSID_H__
#define __RESFS_SYSID_H__

SYS_RESID()
DEF_RESID(RESID_NONE)
DEF_RESID(RESID_FONT)
DEF_RESID(RESID_LANGSTR)
DEF_RESID(RESID_CTRL)
DEF_RESID(RESID_PALETTE)
DEF_RESID(RESID_ICON)
END_RESID(RESID_SYSMAX, 2)

SYS_FONTID()
SET_FONTID(FONTID_MASK, 0x0F)
SET_FONTID(FONTID_PANEL, 0x10)
SET_FONTID(FONTID_OUTLINE, 0x20)
SET_FONTID(FONTID_LANGSTR, 0)
DEF_FONTID(FONTID_DEFAULT)
END_FONTID(FONTID_SYSMAX, 0)

SYS_COLORID()
SET_COLORID(COLORID_ERROR, 0xFF)
SET_COLORID(COLORID_RED, 0xFE)
SET_COLORID(COLORID_GREEN, 0xFD)
SET_COLORID(COLORID_BLUE, 0xFC)
SET_COLORID(COLORID_WHITE, 0xFB)
SET_COLORID(COLORID_BLACK, 0xFA)
SET_COLORID(COLORID_TRANSPARENT, 0xF9)
SET_COLORID(COLORID_TBLACK, 0xF8)
SET_COLORID(COLORID_YELLOW, 0xF7)
SET_COLORID(COLORID_GRAY, 0xF6)
SET_COLORID(COLORID_BLUE1, 0xF5)
SET_COLORID(COLORID_DBLUE, 0xF4)
END_COLORID(COLORID_DUMMY, 0)

SYS_MSGID()
DEF_MSGID(MSG_NONE)
DEF_MSGID(MSG_MENU_ENTER)
DEF_MSGID(MSG_DOC_CHG_POLL)
DEF_MSGID(MSG_DOC_CHG)
END_MSGID(MSGID_SYSMAX, 0)

// SYS_CTRLID ()
//   DEF_CTRLID (CTRLID_GROUP)
//   DEF_CTRLID (CTRLID_TEXT)
//   DEF_CTRLID (CTRLID_ICON)
// END_CTRLID (CTRLID_SYSMAX, 0)

#endif /* __RESFS_SYSID_H__ */
